version: "3.8"

services:
  nginx:
    image: nginx
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
    volumes:
      - ./setup/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    depends_on:
      - php

  php:
    build: setup/docker/php
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: transactions
      DB_USERNAME: transactions
      DB_PASSWORD: transactions
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    command: sh -c "composer install && ./artisan migrate && php-fpm"

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: transactions
      MYSQL_DATABASE: transactions
      MYSQL_USER: transactions
      MYSQL_PASSWORD: transactions
